services:
  cube:
    image: cubejs/cube:latest
    ports:
      - "4000:4000"
      - "15432:15432"
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_TYPE=sqlite
      - CUBEJS_DB_NAME=/data/main_curated.db
    volumes:
      - ./semantic_layer_cube:/cube/conf
      - ./data_warehouse:/data:ro

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=h2
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - ./metabase_data:/metabase-data
